
const pt = {
  title: "Calculadora AposentaCrypto",
  subtitle: "Planejamento Soberano",
  marketData: "Dados de Mercado",
  btcPrice: "Preço BTC",
  rates: "Taxas",
  configTitle: "Dados do beneficiário",
  profile: "Perfil",
  birthDate: "Data de Nascimento",
  currentAge: "Idade Atual",
  retirementAge: "Idade Aposentadoria",
  lifeExpectancy: "Expectativa de Vida",
  retirementModeLabel: "Modo de Aposentadoria",
  modeVitalicio: "Vitalício",
  modeProgramado: "Saque Programado",
  withdrawalRate: "Taxa de Retirada (%)",
  desiredIncome: "Renda Mensal Desejada na aposentadoria",
  avgMonthlyIncome: "Renda Atual",
  financial: "Financeiro",
  initialSavings: "Poupança Inicial",
  monthlyContribution: "Aporte Mensal",
  strategy: "Estratégia",
  btcAllocation: "Alocação em Bitcoin",
  cagr: "CAGR (Crescimento Anual BTC)",
  fixedIncome: "Renda Fixa / Previdência (Anual)",
  inflation: "Inflação Projetada (Anual)",
  results: "Resultados Projetados",
  wealthToday: "Patrimônio Necessário Hoje",
  wealthTodaySub: "Para se aposentar agora",
  finalWealth: "Patrimônio Projetado",
  monthlyIncome: "Renda Mensal Estimada",
  adjustedIncome: "Renda Desejada Ajustada para", 
  realProjectedIncome: "Renda real ajustada para",
  gapAnalysis: "Análise de Viabilidade",
  incomeGap: "Diferença de Renda",
  suggestedContrib: "Sugestão de Aporte Adicional",
  suggestedContribSub: "Para atingir a meta",
  applyContrib: "Aplicar ao Aporte Mensal",
  constructionTime: "Tempo de Aporte", 
  freedomTime: "Tempo de Liberdade",
  retirementDate: "Data Aposentadoria",
  chartIncome: "Renda Mensal",
  chartWealth: "Patrimônio",
  chartContrib: "Contribuição Anual",
  tableDetail: "Planilha Detalhada",
  downloadPdf: "Baixar Relatório PDF",
  disclaimer: "Isenção de Responsabilidade: Esta ferramenta é apenas para fins informativos e educacionais. Não constitui recomendação de investimento. Os resultados são projeções baseadas em premissas configuradas pelo usuário. O desempenho passado não garante resultados futuros.",
  startContrib: "Início de Aporte",
  endContrib: "Fim de Aporte",
  startRetire: "Início Aposentadoria",
  endRetire: "Fim Aposentadoria",
  finalBalance: "Saldo Final",
  configure: "Configurar",
  
  // New Section
  planSectionTitle: "Plano AposentaCrypto",
  comparisonSectionTitle: "Comparativos",
  otherDataTitle: "Outros Dados e Ajustes",
  chartsTitle: "Gráficos",
  legacyWealth: "Patrimônio Restante (Herança)",
  legacyWealthSub: "Para herdeiros",
  
  // Settings Modal
  settingsTitle: "Configurações Avançadas",
  tabINSS: "INSS",
  tabPension: "Previdência Privada",
  tabGeneral: "AposentaCrypto", 
  btnSave: "Salvar Alterações",
  btnCancel: "Cancelar",
  enableGeneralSettings: "Preencher dados AposentaCrypto", 
  
  // INSS Settings
  enableINSS: "Preencher dados do INSS",
  sex: "Sexo",
  male: "Masculino",
  female: "Feminino",
  startContribYear: "Ano início contribuição",
  totalContribTime: "Tempo total estimado (anos)",
  inssDisclaimer: "⚠️ Os dados do calculo do INSS é uma estimativa média, baseada nas regras atuais do INSS e em informações simplificadas. O valor real pode variar conforme histórico de contribuições, mudanças de regras e limites do sistema previdenciário.",
  
  // Pension Settings
  enablePension: "Preencher dados da Previdência",
  pensionModeLabel: "Tipo de Plano",
  currentPensionContrib: "Aporte mensal atual",
  currentPensionPatrimony: "Patrimônio já acumulado",
  yearsContributing: "Há quantos anos contribui",
  pensionDisclaimer: "⚠️ Cálculo simplificado considerando crescimento real do patrimônio e aportes futuros.",

  // General Settings
  globalWithdrawal: "Taxa de retirada CAGR (a.a.)",
  globalHistCAGR: "Valor histórico do CAGR (a.a.)",
  globalINSSCeiling: "Teto Máximo do INSS",
  globalPensionYield: "Rentabilidade média Prev. (Real a.a.)",
  globalInflation: "Inflação Projetada Anual (a.a.)",

  // Strategy Comparison
  compTitle: "Comparativo de Modalidades",
  compMetric: "Métrica",
  compAposenta: "AposentaCrypto",
  compPension: "Previdência Privada",
  compINSS: "INSS",
  compType: "Tipo", 
  compContrib: "Aporte Mensal",
  compTime: "Tempo Contribuição",
  compIncome: "Renda Mensal (Aposentadoria)",
  compWealthRetirement: "Patrimônio na aposentadoria", 
  compWealth: "Patrimônio (Pós-Aposentadoria)",
  compLegacyExpectancy: "Patrimônio de Herança (idade fim dos recursos)", // Changed
  compLegacy: "Patrimônio de Herança",
  compBankruptcyAge: "Idade fim dos recursos",
  compNone: "Nenhum",
  compPerpetual: "Perpétuo",

  tooltips: {
    wealthToday: "Patrimonio necessario para se aposentar hoje com os valores desejados.",
    finalWealth: "Patrimonio projetado para o ano da aposentadoria, com os dados atualizados.",
    monthlyIncome: "Renda passiva mensal estimada que seu patrimônio gerará na aposentadoria, ajustada anualmente pela inflação para manter seu poder de compra.",
    desiredIncome: "Quanto você gostaria de receber mensalmente na sua aposentadoria, baseado na data de hoje?",
    birthDate: "Sua data de nascimento para cálculo da idade atual.",
    retirementAge: "Com qual idade você deseja parar de aportar e começar a usufruir?",
    lifeExpectancy: "Até qual idade você estima viver? Usado para calcular a retirada do principal caso não seja perpétuo.",
    retirementMode: "Vitalicio: Preserva o principal (rende juros). Saque Programado: Consome o principal ao longo do tempo.",
    withdrawal: "Porcentagem do patrimônio total retirada anualmente como renda passiva (Padrão: 4%).",
    savings: "Quanto você já tem acumulado hoje para investir?",
    contribution: "Quanto você vai investir todos os meses até a aposentadoria?",
    avgIncome: "Sua renda média mensal atual.",
    btcAlloc: "Quanto do seu portfólio será em Bitcoin vs Renda Fixa?",
    cagr: "Estimativa de valorização anual média do Bitcoin. Histórico ~100%+, Conservador 12%, Base 20% e Otimista 30%. Estimativa de mercado entre 35% e 45%.",
    fixed: "Rentabilidade anual estimada para a parte em Renda Fixa ou Previdência Privada.",
    inflation: "Perda do poder de compra anual da moeda fiduciaria sugerida pelo governo.",
    t_withdrawalRate: "Taxa segura para retirada anual sem exaurir o patrimônio rapidamente (Trinity Study). Padrão 4%.",
    t_histCAGR: "Média histórica de crescimento do Bitcoin desde sua criação. Padrão 156%.",
    t_inssCeiling: "Valor máximo pago pelo INSS atualmente. Padrão R$ 8.475,55.",
    t_pensionYield: "Rentabilidade real (acima da inflação) esperada para fundos de previdência. Padrão 4%.",
    t_inflation: "Expectativa de inflação média para corrigir valores ao longo do tempo. Padrão 4%.",
    t_inssStartYear: "Ano em que você começou a trabalhar com carteira assinada ou contribuir para o INSS.",
    t_inssTime: "Soma de todos os anos que você já contribuiu para a previdência social.",
    t_inssIncome: "Média dos seus salários de contribuição. Usado para estimar o benefício.",
    t_pensionContrib: "Quanto você deposita mensalmente no seu plano de previdência privada.",
    t_pensionPatrimony: "Saldo atual acumulado no seu fundo de previdência.",
    t_pensionYears: "Há quanto tempo você já possui este plano de previdência.",
    legacyWealth: "Patrimonio que restará para que seja deixado de herança para a família."
  },
  colYear: "Ano",
  colAge: "Idade",
  colPhase: "Fase",
  colContrib: "Aporte/Retirada (Ano)",
  colYield: "Valorização",
  colBalance: "Saldo Final",
  mantras: [
    "“A liberdade é individual, mas transforma o coletivo.”",
    "“Não é sobre ficar rico rápido, é sobre nunca mais ficar sem escolha.”",
    "“Segurança e educação primeiro, resultados depois.”",
    "“Aposentadoria não é parar de trabalhar, é poder escolher o que fazer.”"
  ]
};

const en = {
  title: "AposentaCrypto Calculator",
  subtitle: "Sovereign Planning",
  marketData: "Market Data",
  btcPrice: "BTC Price",
  rates: "Rates",
  configTitle: "Beneficiary Data",
  profile: "Profile",
  birthDate: "Birth Date",
  currentAge: "Current Age",
  retirementAge: "Retirement Age",
  lifeExpectancy: "Life Expectancy",
  retirementModeLabel: "Retirement Mode",
  modeVitalicio: "Lifetime (Annuity)",
  modeProgramado: "Programmed Withdrawal",
  withdrawalRate: "Withdrawal Rate (%)",
  desiredIncome: "Desired Monthly Income in Retirement",
  avgMonthlyIncome: "Current Income",
  financial: "Financial",
  initialSavings: "Initial Savings",
  monthlyContribution: "Monthly Contribution",
  strategy: "Strategy",
  btcAllocation: "Bitcoin Allocation",
  cagr: "CAGR (Annual BTC Growth)",
  fixedIncome: "Fixed Income / Pension (Annual)",
  inflation: "Projected Inflation (Annual)",
  results: "Projected Results",
  wealthToday: "Wealth Needed Today",
  wealthTodaySub: "To retire now",
  finalWealth: "Projected Wealth",
  monthlyIncome: "Estimated Monthly Income",
  adjustedIncome: "Adjusted Desired Income for", 
  realProjectedIncome: "Real Adjusted Income for",
  gapAnalysis: "Feasibility Analysis",
  incomeGap: "Income Gap",
  suggestedContrib: "Suggested Additional Contribution",
  suggestedContribSub: "To reach the goal",
  applyContrib: "Apply to Monthly Contribution",
  constructionTime: "Construction Time",
  freedomTime: "Freedom Time",
  retirementDate: "Retirement Date",
  chartIncome: "Monthly Income",
  chartWealth: "Wealth",
  chartContrib: "Annual Contribution",
  tableDetail: "Detailed Table",
  downloadPdf: "Download PDF Report",
  disclaimer: "Disclaimer: This tool is for informational and educational purposes only. It does not constitute investment advice. Results are projections based on user-configured assumptions. Past performance does not guarantee future results.",
  startContrib: "Start Contribution",
  endContrib: "End Contribution",
  startRetire: "Start Retirement",
  endRetire: "End Retirement",
  finalBalance: "Final Balance",
  configure: "Configure",
  
  // New Section
  planSectionTitle: "AposentaCrypto Plan",
  comparisonSectionTitle: "Comparisons",
  otherDataTitle: "Other Data & Adjustments",
  chartsTitle: "Charts",
  legacyWealth: "Remaining Wealth (Legacy)",
  legacyWealthSub: "Estimated amount for heirs",

  // Settings Modal
  settingsTitle: "Advanced Settings",
  tabINSS: "Social Security",
  tabPension: "Private Pension",
  tabGeneral: "AposentaCrypto",
  btnSave: "Save Changes",
  btnCancel: "Cancel",
  enableGeneralSettings: "Enable AposentaCrypto Data",
  
  // INSS Settings
  enableINSS: "Fill Social Security data",
  sex: "Sex",
  male: "Male",
  female: "Female",
  startContribYear: "Contribution start year",
  totalContribTime: "Estimated total time (years)",
  inssDisclaimer: "⚠️ Social Security calculation data is an average estimate based on current rules and simplified information. The actual value may vary according to contribution history, rule changes, and system limits.",
  
  // Pension Settings
  enablePension: "Fill Pension data",
  pensionModeLabel: "Plan Type",
  currentPensionContrib: "Current monthly contribution",
  currentPensionPatrimony: "Accumulated patrimony",
  yearsContributing: "Years contributing",
  pensionDisclaimer: "⚠️ Simplified calculation considering real patrimony growth and future contributions.",

  // General Settings
  globalWithdrawal: "Withdrawal Rate CAGR (p.a.)",
  globalHistCAGR: "Historical CAGR Value (p.a.)",
  globalINSSCeiling: "Social Security Ceiling",
  globalPensionYield: "Avg Pension Yield (Real p.a.)",
  globalInflation: "Projected Annual Inflation (p.a.)",

  // Strategy Comparison
  compTitle: "Modality Comparison",
  compMetric: "Metric",
  compAposenta: "AposentaCrypto",
  compPension: "Private Pension",
  compINSS: "Social Security",
  compType: "Type", 
  compContrib: "Monthly Contribution",
  compTime: "Contrib. Time",
  compIncome: "Monthly Income (Retirement)",
  compWealthRetirement: "Wealth at Retirement", 
  compWealth: "Wealth (Post-Retirement)",
  compLegacyExpectancy: "Legacy Wealth (at resource depletion age)", // Changed
  compLegacy: "Legacy Wealth",
  compBankruptcyAge: "Resources End Age",
  compNone: "None",
  compPerpetual: "Perpetual",

  tooltips: {
    wealthToday: "Wealth necessary to retire today with desired values.",
    finalWealth: "Projected wealth for the retirement year, with updated data.",
    monthlyIncome: "Estimated monthly passive income your wealth will generate in retirement, adjusted annually for inflation to maintain purchasing power.",
    desiredIncome: "How much would you like to receive monthly in your retirement, based on today's value?",
    birthDate: "Your birth date for current age calculation.",
    retirementAge: "At what age do you wish to stop contributing and start enjoying?",
    lifeExpectancy: "Until what age do you estimate living? Used to calculate principal withdrawal if not perpetual.",
    retirementMode: "Lifetime: Preserves principal. Programmed: Consumes principal over time.",
    withdrawal: "Percentage of total wealth withdrawn annually as passive income (Default: 4%).",
    savings: "How much do you have accumulated today to invest?",
    contribution: "How much will you invest every month until retirement?",
    avgIncome: "Your current average monthly income.",
    btcAlloc: "How much of your portfolio will be in Bitcoin vs Fixed Income?",
    cagr: "Estimated average annual appreciation of Bitcoin. Historical ~100%+, Conservative 12%, Base 20% and Optimistic 30%. Market estimate between 35% and 45%.",
    fixed: "Estimated annual yield for Fixed Income or Private Pension portion.",
    inflation: "Annual loss of purchasing power of fiat currency suggested by the government.",
    t_withdrawalRate: "Safe annual withdrawal rate without exhausting wealth quickly (Trinity Study). Default 4%.",
    t_histCAGR: "Historical average growth of Bitcoin since creation. Default 156%.",
    t_inssCeiling: "Maximum amount paid by Social Security currently. Default R$ 8.475,55.",
    t_pensionYield: "Real yield (above inflation) expected for pension funds. Default 4%.",
    t_inflation: "Average inflation expectation to correct values over time. Default 4%.",
    t_inssStartYear: "Year you started working/contributing.",
    t_inssTime: "Total years contributed so far.",
    t_inssIncome: "Average contribution salary.",
    t_pensionContrib: "Monthly deposit amount.",
    t_pensionPatrimony: "Total accumulated balance.",
    t_pensionYears: "How long you have been contributing.",
    legacyWealth: "Wealth remaining to be left as inheritance for the family."
  },
  colYear: "Year",
  colAge: "Age",
  colPhase: "Phase",
  colContrib: "Contrib./Withdrawal (Year)",
  colYield: "Appreciation",
  colBalance: "Final Balance",
  mantras: [
    "“Freedom is individual, but it transforms the collective.”",
    "“It's not about getting rich quick, it's about never running out of choices.”",
    "“Security and education first, results later.”",
    "“Retirement is not stopping work, it is being able to choose what to do.”"
  ]
};

const es = {
  title: "Calculadora JubilaCrypto",
  subtitle: "Planificación Soberana",
  marketData: "Datos de Mercado",
  btcPrice: "Precio BTC",
  rates: "Tasas",
  configTitle: "Datos del beneficiario",
  profile: "Perfil",
  birthDate: "Fecha de Nacimiento",
  currentAge: "Edad Actual",
  retirementAge: "Edad de Jubilación",
  lifeExpectancy: "Esperanza de Vida",
  retirementModeLabel: "Modo de Jubilación",
  modeVitalicio: "Vitalicio",
  modeProgramado: "Retiro Programado",
  withdrawalRate: "Tasa de Retiro (%)",
  desiredIncome: "Renta Mensual Deseada en jubilación",
  avgMonthlyIncome: "Renta Actual",
  financial: "Financiero",
  initialSavings: "Ahorro Inicial",
  monthlyContribution: "Aporte Mensal",
  strategy: "Estrategia",
  btcAllocation: "Asignación en Bitcoin",
  cagr: "CAGR (Crecimiento Anual BTC)",
  fixedIncome: "Renta Fija / Pensión (Anual)",
  inflation: "Inflación Proyectada (Anual)",
  results: "Resultados Proyectados",
  wealthToday: "Patrimonio Necesario Hoy",
  wealthTodaySub: "Para jubilarse ahora",
  finalWealth: "Patrimonio Proyectado",
  monthlyIncome: "Renta Mensual Estimada",
  adjustedIncome: "Renta Deseada Ajustada para", 
  realProjectedIncome: "Renta Real Ajustada para",
  gapAnalysis: "Análisis de Viabilidad",
  incomeGap: "Diferencia de Renta",
  suggestedContrib: "Sugerencia de Aporte Adicional",
  suggestedContribSub: "Para alcanzar la meta",
  applyContrib: "Aplicar al Aporte Mensal",
  constructionTime: "Tiempo de Construcción",
  freedomTime: "Tiempo de Libertad",
  retirementDate: "Fecha de Jubilación",
  chartIncome: "Renta Mensual",
  chartWealth: "Patrimonio",
  chartContrib: "Contribución Anual",
  tableDetail: "Tabla Detallada",
  downloadPdf: "Descargar Informe PDF",
  disclaimer: "Descargo de responsabilidad: Esta herramienta es solo para fines informativos y educativos. No constituye asesoramiento de inversión. Los resultados son proyecciones basadas en supuestos configurados por el usuario. El rendimiento pasado no garantiza resultados futuros.",
  startContrib: "Inicio de Aporte",
  endContrib: "Fin de Aporte",
  startRetire: "Inicio Jubilación",
  endRetire: "Fin Jubilación",
  finalBalance: "Saldo Final",
  configure: "Configurar",
  
  // New Section
  planSectionTitle: "Plan JubilaCrypto",
  comparisonSectionTitle: "Comparativas",
  otherDataTitle: "Otros Datos y Ajustes",
  chartsTitle: "Gráficos",
  legacyWealth: "Patrimonio Restante (Herencia)",
  legacyWealthSub: "Monto estimado para herederos",

  // Settings Modal
  settingsTitle: "Configuraciones Avanzadas",
  tabINSS: "Seguridad Social",
  tabPension: "Pensión Privada",
  tabGeneral: "JubilaCrypto",
  btnSave: "Guardar Cambios",
  btnCancel: "Cancelar",
  enableGeneralSettings: "Habilitar datos JubilaCrypto",
  
  // INSS Settings
  enableINSS: "Rellenar datos de Seguridad Social",
  sex: "Sexo",
  male: "Masculino",
  female: "Femenino",
  startContribYear: "Año inicio contribución",
  totalContribTime: "Tiempo total estimado (años)",
  inssDisclaimer: "⚠️ Los datos del cálculo de Seguridad Social son una estimación promedio basada en reglas actuales e información simplificada. El valor real puede variar según historial, cambios de reglas y límites.",
  
  // Pension Settings
  enablePension: "Rellenar datos de Pensión",
  pensionModeLabel: "Tipo de Plan",
  currentPensionContrib: "Aporte mensual actual",
  currentPensionPatrimony: "Patrimonio acumulado",
  yearsContributing: "Años contribuyendo",
  pensionDisclaimer: "⚠️ Cálculo simplificado considerando crecimiento real del patrimonio y aportes futuros.",

  // General Settings
  globalWithdrawal: "Tasa de retiro CAGR (a.a.)",
  globalHistCAGR: "Valor histórico del CAGR (a.a.)",
  globalINSSCeiling: "Techo Máximo de Seguridad Social",
  globalPensionYield: "Rentabilidad media Pensión (Real a.a.)",
  globalInflation: "Inflación Proyectada Anual (a.a.)",

  // Strategy Comparison
  compTitle: "Comparativa de Modalidades",
  compMetric: "Métrica",
  compAposenta: "JubilaCrypto",
  compPension: "Pensión Privada",
  compINSS: "Seguridad Social",
  compType: "Tipo", 
  compContrib: "Aporte Mensal",
  compTime: "Tiempo Contrib.",
  compIncome: "Renta Mensual (Jubilación)",
  compWealthRetirement: "Patrimonio en jubilación", 
  compWealth: "Patrimonio (Post-Jubilación)",
  compLegacyExpectancy: "Patrimonio de Herencia (edad fin de recursos)", // Changed
  compLegacy: "Patrimonio de Herencia",
  compBankruptcyAge: "Edad fin de recursos",
  compNone: "Ninguno",
  compPerpetual: "Perpetuo",

  tooltips: {
    wealthToday: "Este valor representa cuánto capital necesitaría tener acumulado HOY para generar su renta deseada inmediatamente, considerando una tasa de retiro segura (ej: 4%). Es su 'Número Mágico' traído a valor presente.",
    finalWealth: "Monto total acumulado en la fecha de su jubilación, fruto del interés compuesto y valorización de Bitcoin.",
    monthlyIncome: "Renta pasiva mensual estimada que su patrimonio generará en la jubilación, ajustada anualmente por inflación para mantener su poder adquisitivo.",
    desiredIncome: "¿Cuánto le gustaría recibir mensualmente en su jubilación, basado en el valor de hoy?",
    birthDate: "Su fecha de nacimiento para cálculo de la edad actual.",
    retirementAge: "¿A qué edad desea dejar de aportar y comenzar a disfrutar?",
    lifeExpectancy: "¿Hasta qué edad estima vivir? Usado para calcular el retiro del principal si no es perpetuo.",
    retirementMode: "Vitalicio: Preserva el principal. Programado: Consume el principal a lo largo del tiempo.",
    withdrawal: "Porcentaje del patrimonio total retirado anualmente como renta pasiva (Defecto: 4%).",
    savings: "¿Cuánto tiene acumulado hoy para invertir?",
    contribution: "¿Cuánto invertirá todos los meses hasta la jubilación?",
    avgIncome: "Su renta media mensual actual.",
    btcAlloc: "¿Cuánto de su portafolio estará en Bitcoin vs Renta Fija?",
    cagr: "Estimación de valorización anual media de Bitcoin. Histórico ~100%+, Conservador 12%, Base 20% y Optimista 30%. Estimación de mercado entre 35% e 45%.",
    fixed: "Rentabilidad anual estimada para la parte en Renta Fija o Pensión Privada.",
    inflation: "Pérdida del poder adquisitivo anual de la moneda fiduciaria sugerida por el gobierno.",
    t_withdrawalRate: "Tasa segura para retiro anual sin agotar el patrimonio rápidamente (Trinity Study). Defecto 4%.",
    t_histCAGR: "Media histórica de crecimiento de Bitcoin desde su creación. Defecto 156%.",
    t_inssCeiling: "Valor máximo pagado por Seguridad Social actualmente. Defecto R$ 8.475,55.",
    t_pensionYield: "Rentabilidad real (sobre inflación) esperada para fondos de pensión. Defecto 4%.",
    t_inflation: "Expectativa de inflación media para corregir valores a lo largo del tiempo. Defecto 4%.",
    t_inssStartYear: "Año en que comenzó a trabajar/contribuir.",
    t_inssTime: "Suma de todos los años que ya contribuyó.",
    t_inssIncome: "Media de sus salarios de contribución.",
    t_pensionContrib: "Cuánto deposita mensualmente en su plan.",
    t_pensionPatrimony: "Saldo actual acumulado.",
    t_pensionYears: "Hace cuánto tiempo posee este plan.",
    legacyWealth: "Valor estimado del patrimonio que quedará después del período de expectativa de vida. Si el modo es Vitalicio, el principal se conserva."
  },
  colYear: "Año",
  colAge: "Edad",
  colPhase: "Fase",
  colContrib: "Aporte/Retirada (Año)",
  colYield: "Valorización",
  colBalance: "Saldo Final",
  mantras: [
    "“La libertad es individual, pero transforma lo colectivo.”",
    "“No se trata de hacerse rico rápido, se trata de nunca más quedarse sin opciones.”",
    "“Seguridad y educación primero, resultados después.”",
    "“La jubilación no es dejar de trabajar, es poder elegir qué hacer.”"
  ]
};

export const translations = {
  pt,
  en,
  es
};
